### ISSUE TITLE
Support cluster events 

### ISSUE THREAD

**Issue by ronenhamias** [servicefabric/servicefabric#33] opened 2015-09-08 11:01 UTC
Subscribe to change notifications of the cluster membership The events to track the life-cycle of members are:

MemberUp - A new member has joined the cluster and its status has been changed to Up.
MemberExited - A member is leaving the cluster and its status has been changed to Exiting Note that the node might already have been shutdown when this event is published on another node.
MemberRemoved - Member completely removed from the cluster.
UnreachableMember - A member is considered as unreachable, detected by the failure detector of at least one other node.
ReachableMember - A member is considered as reachable again, after having been unreachable. All nodes that previously detected it as unreachable has detected it as reachable again.

**Comment by myroslavlisniak** [comment] 2015-09-08 14:41
Closed as duplicate of https://github.com/servicefabric/servicefabric/issues/29
Please add comment there

**Closed by myroslavlisniak** 2015-09-08 14:41 UTC
Labels: feature, improvement
